run2: ProgramTest2.o Program2.o
		gcc -o run2 ProgramTest2.o Program2.o
Program2.o: Program2.c
		gcc -c Program2.c
ProgramTest2.o: ProgramTest2.c
		gcc -c ProgramTest2.c

run: ProgramTest1.o Program1.o
		gcc -o run ProgramTest1.o Program1.o
Program1.o: Program1.c
		gcc -c Program1.c
ProgramTest1.o: ProgramTest1.c
		gcc -c ProgramTest1.c
